config/routes.rb
Rails.application.routes.draw do
	
	get '/posts/:post_id/like' => 'posts#like'
	get '/venues' => 'application#create_venue'
	resources :likes
	resources :posts
	devise_for :users
	root 'posts#index'
	post '/venues' => 'application#add_tip'
	
end

app/models/like.rb
class Like < ActiveRecord::Base
	belongs_to :post
	belongs_to :user
end

app/models/post.rb
class Post < ActiveRecord::Base
	validates :user, presence: true, strict: true
	belongs_to :user
	has_many :likes
	has_many :users, through: :likes
	# validates :foursquare_id, presence: true

	# def venue
 #        Venue.find_by(foursquare_id: self.foursquare_id)
 #    end
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :posts
  has_many :liked_posts, through: :likes, as: :liked_posts
  has_many :likes

	def toggle_like(post)
		like = Like.find_or_initialize_by(user_id: self.id, post_id: post.id)
		
		if (like.persisted?)
			like.destroy
		else
			like.save
		end
	end

end

app/models/venue.rb
class Venue < ActiveRecord::Base
	has_many :posts
	serialize :data
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  def add_tip
     @post = Post.new(post_params)
     @post.user = current_user
     @post.save!


     render json: @post
 end

 private

 def post_params
     params.require(:post).permit(:foursquare_id)
 end

end

app/controllers/likes_controller.rb
class LikesController < ApplicationController
  before_action :set_like, only: [:show, :edit, :update, :destroy]

  # GET /likes
  # GET /likes.json
  def index
    @likes = Like.all
  end

  # GET /likes/1
  # GET /likes/1.json
  def show
  end

  # GET /likes/new
  def new
    @like = current_user.likes.build
  end

  # GET /likes/1/edit
  def edit
  end

  # POST /likes
  # POST /likes.json
  def create
    @like = current_user.likes.build(like_params)

    respond_to do |format|
      if @like.save
        format.html { redirect_to @like, notice: 'Like was successfully created.' }
        format.json { render :show, status: :created, location: @like }
      else
        format.html { render :new }
        format.json { render json: @like.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /likes/1
  # PATCH/PUT /likes/1.json
  def update
    respond_to do |format|
      if @like.update(like_params)
        format.html { redirect_to @like, notice: 'Like was successfully updated.' }
        format.json { render :show, status: :ok, location: @like }
      else
        format.html { render :edit }
        format.json { render json: @like.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /likes/1
  # DELETE /likes/1.json
  def destroy
    @like.destroy
    respond_to do |format|
      format.html { redirect_to likes_url, notice: 'Like was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_like
      @like = Like.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def like_params
      params.require(:like).permit(:user_id, :post_id)
    end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, except: [:show]

  # GET /posts
  # GET /posts.json
  def index
    if params[:foursquare_id]
      @posts = Post.where(foursquare_id: params[:foursquare_id])
    else
      @posts = Post.all
    end
  end

  # GET /posts/1
  # GET /posts/1.json
  def show
  end

  # GET /posts/new
  def new
    @post = current_user.posts.build
  end

  # GET /posts/1/edit
  def edit
  end

  # POST /posts
  # POST /posts.json
  def create
    @post = current_user.posts.build(post_params)

    respond_to do |format|
      if @post.save
        format.html { redirect_to @post, notice: 'Post was successfully created.' }
        format.json { render :show, status: :created, location: @post }
      else
        format.html { render :new }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  def like
    post = Post.find(params[:post_id])
    current_user.toggle_like(post)

    redirect_to "/posts"
  end

  # PATCH/PUT /posts/1
  # PATCH/PUT /posts/1.json
  def update
    respond_to do |format|
      if @post.update(post_params)
        format.html { redirect_to @post, notice: 'Post was successfully updated.' }
        format.json { render :show, status: :ok, location: @post }
      else
        format.html { render :edit }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1
  # DELETE /posts/1.json
  def destroy
    @post.destroy
    respond_to do |format|
      format.html { redirect_to posts_url, notice: 'Post was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_post
      @post = Post.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def post_params
      params.require(:post).permit(:title, :content, :user_id)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/likes_helper.rb
module LikesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Cookie Monster</title>
  <link href='http://fonts.googleapis.com/css?family=Nunito' rel='stylesheet' type='text/css'>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <nav class="navbar navbar-default navbar-fixed-top">
    <div class="container">
        <a class="navbar-brand" href="/"><img style="max-width:300px; margin-top: -7px; "
             src="http://i.imgur.com/VdIpsez.png"></a>
        <% if current_user %>
          <ul class="nav navbar-nav navbar-right">
            <li><button type="button" class="btn btn-default navbar-btn"><%= link_to "Sign Out", destroy_user_session_path, method: 'DELETE'  %></button></li>
          </ul>
        <% end %>
      <!-- </div> -->
    </div>
  </nav>

  <p class="bg-success"></p>
  <p class="bg-warning"></p>

  <%= yield %>

  <footer class="navbar navbar-default navbar-fixed-bottom">
    <div class="panel-footer">
      <p class="text-muted">&copy; 2015 Cookie Monster LLC</p>
    </div>
  </footer>
</body>
</html>

app/views/likes/_form.html.erb
<%= form_for(@like) do |f| %>
  <% if @like.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@like.errors.count, "error") %> prohibited this like from being saved:</h2>

      <ul>
      <% @like.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :user_id %><br>
    <%= f.number_field :user_id %>
  </div>
  <div class="field">
    <%= f.label :post_id %><br>
    <%= f.number_field :post_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/likes/edit.html.erb
<h1>Editing Like</h1>

<%= render 'form' %>

<%= link_to 'Show', @like %> |
<%= link_to 'Back', likes_path %>

app/views/likes/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Likes</h1>

<table>
  <thead>
    <tr>
      <th>User</th>
      <th>Post</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @likes.each do |like| %>
      <tr>
        <td><%= like.user_id %></td>
        <td><%= like.post_id %></td>
        <td><%= link_to 'Show', like %></td>
        <td><%= link_to 'Edit', edit_like_path(like) %></td>
        <td><%= link_to 'Destroy', like, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Like', new_like_path %>

app/views/likes/new.html.erb
<h1>New Like</h1>

<%= render 'form' %>

<%= link_to 'Back', likes_path %>

app/views/likes/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>User:</strong>
  <%= @like.user_id %>
</p>

<p>
  <strong>Post:</strong>
  <%= @like.post_id %>
</p>

<%= link_to 'Edit', edit_like_path(@like) %> |
<%= link_to 'Back', likes_path %>

app/views/posts/_form.html.erb
<%= form_for(@post) do |f| %>
  <% if @post.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@post.errors.count, "error") %> prohibited this post from being saved:</h2>

      <ul>
      <% @post.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <%= f.hidden_field :foursquare_id %>
  <div class="field">
    <p class="form-title"><strong>Venue</strong></p>
    <!-- < % = f.label :title %> --><br>
    <%= f.text_field :title, class: 'form-control' %>
  </div>
  <div class="field">
    <p class="form-title"><strong>Tip</strong></p>
    <!-- < %= f.label :content, class: 'form-group' %><br> -->
    <%= f.text_area :content, class: 'form-control' %>
  </div>
  <div class="actions">
    <%= f.submit "Add Tip", class: 'btn btn-default' %>
  </div>
<% end %>

app/views/posts/edit.html.erb
<h1 class="form-heading">Editing Tip</h1>

<%= render 'form' %>

<div class="form-links">
	<%= link_to 'Back', posts_path %>
</div>

app/views/posts/index.html.erb
<html>
<head>
  <p class="bg-success" data-dismiss="alert"><%= notice %></p>

    <script src="https://ajax.googleapis.com/ajax/libs/jquery/2.1.3/jquery.min.js"></script>
    <script src="https://maps.googleapis.com/maps/api/js?sensor=false&libraries=places"></script>
    <title></title>
</head>
<body>
  <div class="container">

    <div class="row row-centered">
      <div class="col-xs-12 col-centered">
        <p class="lead">Welcome to the Cookie Monster, the best cookie finder app on the internets (Ted Stevens would be proud). Your hot and fresh cookies are waiting for you below. Let's get snackin', you little cookie monster you!</p>
      </div>
    </div>

    <div class="row row-centered">
      <div class="venue-wrapper col-md-6 col-centered">
        <h1>Search Results:</h1>
          <div id="venues"></div>
      </div>
      <div class="map-wrapper col-md-6 col-centered">
      <div id="map"></div>
      <div class="comments-wrapper col-sm-12 col-centered">
        <h1>What People Are Saying Nearby:</h1>
          <div class="tips-headers">
          <table>
            <thead>
              <tr>
                <th>Venue</th>
                <th>Username</th>
                <th>Tip</th>
                <th colspan="3"></th>
              </tr>
            </thead>
              </div>

            <tbody>
              <% @posts.each do |post| %>
                <tr>
                  <td><%= post.title %></td>
                  <td><%= post.user.email %></td>
                  <td><%= post.content %></td>
                    <% if post.user == current_user %>
                      <td><%= link_to 'Edit', edit_post_path(post) %></td>
                      <td><%= link_to 'Delete', post, method: :delete, data: { confirm: 'Are you sure?' } %></td>
                    <% end %>
                    <% if current_user.likes.where(post_id: post.id) != [] %>
                      <td><%= link_to 'Like', "/posts/#{post.id}/like", class: 'like_post liked' %></td>
                      <% else %>
                      <td><%= link_to 'Like', "/posts/#{post.id}/like", class: 'like_post' %></td>
                <% end %>
                </tr>
              <% end %>
            </tbody>
          </table>
          <br>
            <%= link_to 'New Post', new_post_path, class: 'btn btn-default' %>
          </div>
      </div>
      </div>
    </div>

    <div class="row row-centered">
    </div>

  </div>
</body>
</html>

app/views/posts/new.html.erb
<h1 class="form-heading">New Tip</h1>

<%= render 'form' %>

<div class="form-links">
	<%= link_to 'Back', posts_path %>
</div>

app/views/posts/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Venue:</strong>
  <%= @post.title %>
</p>

<p>
  <strong>Tip:</strong>
  <%= @post.content %>
</p>

<%= link_to 'Edit', edit_post_path(@post) %> |
<%= link_to 'Back', posts_url %>

app/views/users/create.html.erb
<h1>Users#create</h1>
<p>Find me in app/views/users/create.html.erb</p>

app/views/users/destroy.html.erb
<h1>Users#destroy</h1>
<p>Find me in app/views/users/destroy.html.erb</p>

app/views/users/edit.html.erb
<h1>Users#edit</h1>
<p>Find me in app/views/users/edit.html.erb</p>

app/views/users/index.html.erb
<h1>Welcome to the user page!</h1>

app/views/users/new.html.erb
<h1>Users#new</h1>
<p>Find me in app/views/users/new.html.erb</p>

app/views/users/show.html.erb
<h1>Users#show</h1>
<p>Find me in app/views/users/show.html.erb</p>

app/views/users/update.html.erb
<h1>Users#update</h1>
<p>Find me in app/views/users/update.html.erb</p>